export let config = {
    "token": "NTk2NjgxMjY1NjU1MTg1NDM4.XSHhpQ.84idsAGS8rxrlVzfzT5MfwHpvlA",
    "prefix": "!!",
    "commands": [
        "testcommand",
        "kick",
        "ban",
        "unban",
        "prune",
        "serverinfo",
        "announce",
        "mute",
        "tempmute",
        "unmute",
        "wyr",
        "tag",
        "say",
        "ramon",
        "rn",
        "dnd",
        "online",
        "lebber",
        "mutechat",
        "unmutechat",
        "setstatus",
        "dog",
        "nood",
    ]
}